<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<link rel="stylesheet" type="text/css" href="style.css"/>
</head>
<body>
<img style="position:absolute;top:3.22in;left:0.43in;width:8.15in;height:6.97in" src="ci_1.png" />
<img style="position:absolute;top:3.43in;left:0.43in;width:2.53in;height:0.38in" src="ci_2.png" />
<img style="position:absolute;top:3.81in;left:0.43in;width:2.53in;height:0.38in" src="ci_3.png" />
<div style="position:absolute;top:3.52in;left:0.90in;width:1.64in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529">MODE DE REGLEMENT</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.90in;left:1.53in;width:0.37in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">Cash</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<img style="position:absolute;top:3.43in;left:3.23in;width:2.53in;height:0.38in" src="ci_4.png" />
<img style="position:absolute;top:3.81in;left:3.23in;width:2.53in;height:0.38in" src="ci_5.png" />
<div style="position:absolute;top:3.52in;left:3.81in;width:1.41in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529">DATE D&apos;ECHEANCE</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.90in;left:4.13in;width:0.77in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">13-09-2018</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<img style="position:absolute;top:3.43in;left:6.03in;width:2.53in;height:0.38in" src="ci_6.png" />
<img style="position:absolute;top:3.81in;left:6.03in;width:2.53in;height:0.38in" src="ci_7.png" />
<div style="position:absolute;top:3.52in;left:7.15in;width:0.32in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529">TVA</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.90in;left:6.60in;width:1.42in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">BE000000300303030</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<img style="position:absolute;top:4.40in;left:0.43in;width:8.15in;height:0.74in" src="ci_8.png" />
<div style="position:absolute;top:4.49in;left:1.14in;width:1.03in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529">DESIGNATION</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.49in;left:3.16in;width:0.33in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529">QTE</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.49in;left:4.28in;width:0.28in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529">P.U</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.49in;left:5.37in;width:0.40in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529">Unité</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.49in;left:6.53in;width:0.55in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529">H.T.V.A</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.49in;left:7.84in;width:0.40in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529">T.V.A</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.86in;left:0.51in;width:0.92in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">carte de visite</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.86in;left:3.27in;width:0.12in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">1</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.86in;left:4.50in;width:0.48in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">150,00</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.86in;left:5.38in;width:0.38in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">pièce</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.86in;left:6.96in;width:0.48in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">150,00</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:4.86in;left:8.14in;width:0.40in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">31,50</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.37in;left:0.43in;width:0.75in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">Remarque:</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<img style="position:absolute;top:5.71in;left:0.43in;width:3.24in;height:1.40in" src="ci_9.png" />
<div style="position:absolute;top:5.80in;left:0.70in;width:0.37in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529">Taux</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.80in;left:1.71in;width:0.38in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529">Base</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.80in;left:2.78in;width:0.59in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529">Montant</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.18in;left:0.95in;width:0.32in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">0.00</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.40in;left:0.95in;width:0.32in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">6.00</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.61in;left:0.87in;width:0.40in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">18.00</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.83in;left:0.87in;width:0.40in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">21.00</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.18in;left:1.93in;width:0.44in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">0,00 €</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.40in;left:1.93in;width:0.44in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">0,00 €</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.61in;left:1.93in;width:0.44in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">0,00 €</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.83in;left:1.84in;width:0.52in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">31,50 €</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.18in;left:3.15in;width:0.44in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">0,00 €</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.40in;left:3.15in;width:0.44in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">0,00 €</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.61in;left:3.15in;width:0.44in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">0,00 €</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.83in;left:3.07in;width:0.52in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">31,50 €</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<img style="position:absolute;top:5.71in;left:5.33in;width:3.24in;height:1.88in" src="ci_10.png" />
<div style="position:absolute;top:5.80in;left:5.96in;width:0.61in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529">Total HT</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:5.81in;left:7.94in;width:0.60in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">150,00 €</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.18in;left:6.10in;width:0.32in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529">TVA</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.18in;left:8.02in;width:0.52in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">31,50 €</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.55in;left:5.92in;width:0.70in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529">Total TTC</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.56in;left:7.94in;width:0.60in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">181,50 €</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.93in;left:5.94in;width:0.65in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529">Acompte</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:6.93in;left:8.10in;width:0.44in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">0,00 €</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.31in;left:5.86in;width:0.81in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529">Net à payer</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:7.31in;left:8.05in;width:0.48in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529">181,50</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529"> </span><br/></SPAN></div>
<img style="position:absolute;top:8.02in;left:0.43in;width:8.15in;height:0.01in" src="ci_11.png" />
<img style="position:absolute;top:10.17in;left:0.43in;width:8.15in;height:0.01in" src="ci_12.png" />
<img style="position:absolute;top:8.02in;left:0.43in;width:0.01in;height:2.16in" src="ci_13.png" />
<img style="position:absolute;top:8.02in;left:8.57in;width:0.01in;height:2.16in" src="ci_14.png" />
<div style="position:absolute;top:8.04in;left:0.57in;width:3.65in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">1. Toutes nos factures sont payables au grand comptant.</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.26in;left:0.57in;width:7.52in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">2. Les montants dus doivent être virés en euro au compte bancaire de Company XXXX , en mentionnent le numéro de</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.47in;left:0.57in;width:4.31in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">présente facture au plus tard 15 jours après la réception de celle-ci.</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.69in;left:0.57in;width:7.60in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">3. En cas de paiement tardive, les sommes dues seront augmentées, de plein droit et sans mise en demeure préalable,</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:8.90in;left:0.57in;width:7.81in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">d’un intérêt de retard, correspondent au taux légal. En autre, une indemnité forfaitaire égal à 15% du montant de la facture,</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.12in;left:0.57in;width:6.36in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">avec un minimum de 100€, sera due pour les frais administratifs générés par ce retard de paiement.</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.33in;left:0.57in;width:7.49in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">4. Toutes contestation relative à la facture doit parvenir par courrier recommandée à Company XXXX , address XXXX</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.55in;left:0.57in;width:7.74in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">postcode XXXX city XXXX , dans les 8 jours qui suivent l’envoi dudit document, faute de quoi la contestation ne pourra en</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.76in;left:0.57in;width:4.40in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">aucun cas être prise en considération. La date de la poste faisant foi.</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:9.98in;left:0.57in;width:5.19in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">5. En cas de contestation persistante, les tribunaux de Bruxelles sont compétents</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<img style="position:absolute;top:0.27in;left:0.43in;width:8.15in;height:2.95in" src="ci_15.png" />
<img style="position:absolute;top:0.27in;left:0.43in;width:1.34in;height:1.34in" src="ri_1.png" />
<div style="position:absolute;top:1.61in;left:0.43in;width:2.56in;line-height:0.27in;"><span style="font-style:normal;font-weight:bold;font-size:14pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">Company Cloud Bill SPRL</span><span style="font-style:normal;font-weight:bold;font-size:14pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.95in;left:0.43in;width:1.53in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">Avenue de la Roue 155</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:2.17in;left:0.43in;width:0.98in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">1000 Bruxelles</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:2.38in;left:0.43in;width:0.60in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">Belgique</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:2.60in;left:0.43in;width:1.42in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">TVA : BE0123456789</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:2.81in;left:0.43in;width:2.07in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">IBAN : BE1234 5678 9123 4567</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:3.03in;left:0.43in;width:1.06in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">BIC : BEBEBEB</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<img style="position:absolute;top:0.27in;left:5.33in;width:3.24in;height:0.51in" src="ci_16.png" />
<img style="position:absolute;top:0.87in;left:5.33in;width:0.74in;height:0.38in" src="ci_17.png" />
<img style="position:absolute;top:0.87in;left:6.08in;width:1.18in;height:0.38in" src="ci_18.png" />
<img style="position:absolute;top:0.87in;left:7.26in;width:1.31in;height:0.38in" src="ci_19.png" />
<img style="position:absolute;top:1.25in;left:5.33in;width:0.74in;height:0.38in" src="ci_20.png" />
<img style="position:absolute;top:1.25in;left:6.08in;width:1.18in;height:0.38in" src="ci_21.png" />
<img style="position:absolute;top:1.25in;left:7.26in;width:1.31in;height:0.38in" src="ci_22.png" />
<div style="position:absolute;top:0.43in;left:5.79in;width:2.39in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529">Bon De Commande N° : 2018.0001</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.96in;left:5.50in;width:0.44in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529">PAGE</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.96in;left:6.47in;width:0.43in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529">DATE</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:0.96in;left:7.65in;width:0.56in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529">CLIENT</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QPAAAA+NimbusSanL-Bold;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.34in;left:5.61in;width:0.24in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">1/1</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.34in;left:6.30in;width:0.77in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">04-09-2018</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.34in;left:7.50in;width:0.86in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">2018CL0001</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.73in;left:5.33in;width:0.75in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">John Ulens</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:1.94in;left:5.33in;width:1.27in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">rue de la fabrique 3</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:2.16in;left:5.33in;width:1.64in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">1000 bruxelles , Belgique</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:2.37in;left:5.33in;width:1.82in;line-height:0.18in;"><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">TVA : BE000000300303030</span><span style="font-style:normal;font-weight:bold;font-size:9pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<img style="position:absolute;top:11.90in;left:0.43in;width:8.15in;height:0.84in" src="ci_23.png" />
<div style="position:absolute;top:12.13in;left:2.37in;width:4.29in;line-height:0.14in;"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">Company Cloud Bill SPRL - Adresse: Avenue de la Roue 155, 1000, Bruxelles, Belgique</span><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
<div style="position:absolute;top:12.44in;left:1.71in;width:5.62in;line-height:0.14in;"><a href="mailto:test@cloudbill.be"><span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529">TEL: +32 2 123 45 67 - MOBILE: +32 488 12 34 56 - FAX: - - E-mail: test@cloudbill.be - Site Web: www.cloudbill.be</span></a>
<span style="font-style:normal;font-weight:bold;font-size:7pt;font-family:QUAAAA+NimbusSanL-Regu;color:#212529"> </span><br/></SPAN></div>
</body>
</html>